[programs.localnet]
sleague_mutilsig = "AHE3asxFy6AREZxDMz88PcGTpX2776Yry8Xp3WPMsiFN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/wes/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
